---
title: "Python基础：异常处理"
url: "post/python-basic-exception-handling"
date: 2020-11-13T19:00:45+08:00
keywords: ''
description: ''
tags: ['Python']
categories: []
draft: true
---

## 触发异常

创建 division.py 文件

```Python
result = 2 / 0
print(result)
```

程序报错：
```
Traceback (most recent call last):
  File "division.py", line 1, in <module>
    result = 2 / 0
ZeroDivisionError: division by zero
```

## 捕获异常

```Python
try:
  result = 2 / 0
  print(result)
except ZeroDivisionError:
  print('除数不能为0')

# output: 除数不能为0
```

## try-except-else

出错时捕获异常，成功时执行else代码块。

```Python
print('给两个数字，计算商：(按q退出)')

while True:
  first_number = input('被除数：')
  if first_number == 'q':
    break
  second_number = input('除数：')
  try:
    answer = int(first_number) / int(second_number)
  except ZeroDivisionError:
    print('警告：除数不能为0')
  else:
    print(answer)
```

## 异常类型

1、ZeroDivisionError 
除数为 0 引发此异常

```Python
print(1/0)

# ZeroDivisionError: division by zero
```

2、FileNotFoundError
文件不存在引发此异常

```Python
with open('nimei.txt') as file_reader:
  print(file_reader.read())

# FileNotFoundError: [Errno 2] No such file or directory: 'nimei.txt'
```

3、NameError
访问未声明的变量引发此异常

```Python
print(message)

# NameError: name 'message' is not defined
```

4、KeyError
字典中查找不存在的关键字引发此异常

```Python
people = {'name': 'jim'}
print(people['name'])
print(people['age'])

# KeyError: 'age'
```

5、AttributeError
访问的对象属性不存在时抛出的异常

```Python
people = {'name': 'jim'}
print(people.len)

# AttributeError: 'dict' object has no attribute 'len'
```

6、IndexError
列表超出索引范围引发此异常

```Python
colors = ['red', 'green', 'blue']
print(colors[3])

# IndexError: list index out of range
```





